DROP TABLE Areas;
CREATE TABLE Areas (
_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
user_id INT(11) DEFAULT NULL,
createdAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAt datetime DEFAULT NULL,
verbatim_id VARCHAR(255) DEFAULT NULL,
name VARCHAR(255) NOT NULL,
type VARCHAR(255) NOT NULL,
geom GEOMETRY NOT NULL
) ENGINE = InnoDB;

ALTER TABLE Areas ADD SPATIAL KEY (geom);


