CREATE VIEW `darwincoreview` AS 
select 'https://creativecommons.org/licenses/by-nc/4.0/' AS `dcterms:license`,
'Danish mycological society (2016-01-13). Fungal records database, contributed by Frøslev, T., Heilmann-Clausen, J., Jeppesen, T.S., Lange, C., Læssøe, T., Petersen, J.H., Søchting, U., Vesterholt, J, online www.svampeatlas.dk' AS `dcterms:bibliographicCitation`,
'HUMAN_OBSERVATION' AS `basisOfRecord`,
'da' AS `dcterms:language`,
`gbiffungi`.`AtlasIDnummer` AS `occurrenceID`,
`gbiffungi`.`AtlasIDnummer` AS `catalogNumber`,
if((`gbiffungi`.`Substrate` = ''),NULL,concat('{"Substrate":"',`gbiffungi`.`Substrate`,'"}')) AS `dynamicProperties`,
`gbiffungi`.`associatedOrganism` AS `associatedTaxa`,
`gbiffungi`.`Leg` AS `recordedBy`,
`gbiffungi`.`VegType` AS `habitat`,
`gbiffungi`.`date_day` AS `day`,
`gbiffungi`.`date_month` AS `month`,
`gbiffungi`.`date_year` AS `year`,
'Europe' AS `continent`,
'Denmark' AS `country`,
`gbiffungi`.`AtlasUserLati` AS `decimalLatitude`,
`gbiffungi`.`AtlasUserLong` AS `decimalLongitude`,
`gbiffungi`.`AtlasUserPrec` AS `coordinatePrecision`,
'WGS84' AS `geodeticDatum`,
`gbiffungi`.`localityBasicString` AS `locality`,
`gbiffungi`.`AtlasLocID` AS `localityID`,
`gbiffungi`.`Det` AS `identifiedBy`,
`gbiffungi`.`GenusName` AS `genus`,
`gbiffungi`.`FullName` AS `scientificName`,
concat('urn:lsid:indexfungorum.org:names:',`gbiffungi`.`FUNIndex`) AS `scientificNameID`,
`gbiffungi`.`DKName` AS `vernacularName`,
`gbiffungi`.`CollNr` AS `fieldNumber` from `gbiffungi` where (`gbiffungi`.`AtlasForumVali` in ('Godkendt','OK'));

