CREATE TABLE IF NOT EXISTS Determination (
  _id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT ,
  createdAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt datetime DEFAULT NULL,
  score INT(11) DEFAULT 0, 
  FOREIGN KEY (yuser_id) REFERENCES User(_id),
  FOREIGN KEY (taxon_id) REFERENCES Taxon(_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;